name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nikhilmhatre0317/nodejs-prod-template
      - name: Publish image to docker hub
        run: docker push nikhilmhatre0317/nodejs-prod-template:latest

  deploy:
    needs: build
    runs-on: [my-backend-test]
    steps:
      - name: Pull image from docker hub
        run: docker pull nikhilmhatre0317/nodejs-prod-template:latest
      - name: Delete old container
        run: docker rm -f nodejs-prod-template-container
      - name: Run docker container
        run: docker run -d -p 4757:4757 --name nodejs-prod-template-container nikhilmhatre0317/nodejs-prod-template
